### ISSUE TITLE
Check criteria for SPs asserting REFEDS R&S entity category

### ISSUE THREAD

**Issue by alexstuart** [ukf/ukf-meta#6]
The criteria for this entity category that can be tested automatically are:

    4.3.1 The Service Provider [...] supports SAML V2.0 HTTP-POST binding.
    4.3.3 The Service Provider provides an mdui:DisplayName and mdui:InformationURL in metadata.
    4.3.4 The Service Provider provides one or more technical contacts in metadata.
    4.3.5 The Service Provider provides requested attributes in metadata.

https://refeds.org/category/research-and-scholarship/

**Comment by iay** [comment]
Moved to GitLab.
