### ISSUE TITLE
Check for empty shibmd:Scope elements

### ISSUE THREAD

**Issue by alexstuart** [ukf/ukf-meta#7]
An IdP with `<shibmd:Scope regexp="false"/>` got imported into the UKf metadata aggregate. No errors are thrown during metadata generation. However, when a Shibboleth SP downloads the metadata, it throws:
```
ERROR OpenSAML.MetadataProvider.XML : metadata instance failed manual validation checking: Scope must have TextContent.
```

The offending entity has been explicitly blacklisted in the UKf metadata aggregation process, so that blacklist will need updating when the generic check has been written.

**Comment by iay** [comment]
Fixed in svn rev 15599, git d6df2247938734f6381eabecf4949cc61ac2503e.
